# Generated by Django 4.2.16 on 2025-03-04 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0003_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
