from django.db import models
from datasets.models import Dataset
# Create your models here.
class LayerWebMap(models.Model):
    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE, related_name='layer_web_maps_id')
    enabled = models.BooleanField()
    zoomToLayer = models.BooleanField()
    logscale= models.BooleanField()
    url = models.CharField(max_length=2000)
    layer_title = models.CharField(max_length=255)
    layer_type = models.CharField(max_length=255)
    is_timeseries = models.BooleanField()
    datetime_format = models.CharField(max_length=255)
    image_format = models.CharField(max_length=255)
    layer_name = models.CharField(max_length=255)
    transparent = models.BooleanField()
    update_transparency = models.BooleanField()
    style = models.CharField(max_length=255)
    colormin = models.FloatField()
    colormax = models.FloatField()
    update_color = models.BooleanField()
    abovemaxcolor = models.CharField(max_length=255)
    belowmincolor = models.CharField(max_length=255)
    numcolorbands = models.IntegerField(default=250)
    timeIntervalStart = models.DateTimeField()
    timeIntervalEnd = models.DateTimeField()
    has_specific_timestep = models.BooleanField()
    specific_timestemps = models.TextField(null=True,blank=True)
    period = models.CharField(max_length=255)
    interval_step = models.CharField(max_length=255,null=True,blank=True)
    opacity = models.FloatField(null=True,blank=True)
    legend_url = models.CharField(max_length=500)
    update_legend = models.BooleanField()
    is_composite = models.BooleanField()
    composite_layer_id = models.CharField(max_length=2000,null=True,blank=True)
    enable_get_map = models.BooleanField()
    get_map_url = models.CharField(max_length=2000,null=True,blank=True)
    get_map_names = models.CharField(max_length=2000,null=True,blank=True)
    no_of_plots = models.IntegerField(default=999)
    enable_chart_timeseries = models.BooleanField()
    timeseries_url = models.CharField(max_length=2000,null=True,blank=True)
    timeseries_variables = models.CharField(max_length=2000,null=True,blank=True)
    timeseries_variable_label = models.CharField(max_length=2000,null=True,blank=True)
    enable_chart_table = models.BooleanField()
    table_url = models.CharField(max_length=2000,null=True,blank=True)
    table_variables = models.CharField(max_length=2000,null=True,blank=True)
    table_variable_label = models.CharField(max_length=2000,null=True,blank=True)
    has_depth = models.BooleanField()
    update_thredds = models.BooleanField()
    restricted = models.BooleanField()
    enable_cog = models.BooleanField()
    cog_params = models.CharField(max_length=2000,null=True,blank=True)
    def __str__(self):
        return f"{self.layer_title}"