# Generated by Django 4.2.16 on 2025-03-04 20:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0003_project_content"),
        ("country", "0002_alter_country_east_bound_longitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TailoredMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "display_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "children",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="project.project"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country_id",
                        to="country.country",
                    ),
                ),
            ],
        ),
    ]
