# Generated by Django 4.2.16 on 2024-09-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submenu_3", "0002_submenu3_content"),
        ("submenu_2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submenu2",
            name="children",
            field=models.ManyToManyField(
                related_name="submenu3", to="submenu_3.submenu3"
            ),
        ),
    ]
