# Generated by Django 4.2.16 on 2024-09-06 02:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submenu_2", "0002_submenu2_children"),
    ]

    operations = [
        migrations.AddField(
            model_name="submenu2",
            name="content",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
