# Generated by Django 4.2.16 on 2024-09-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submenu_2", "0004_alter_submenu2_children"),
    ]

    operations = [
        migrations.AddField(
            model_name="submenu2",
            name="display_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
