# Generated by Django 4.2.16 on 2024-09-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp_product", "0003_webproduct_layer_information"),
        ("submenu_3", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submenu3",
            name="content",
            field=models.ManyToManyField(
                related_name="Content_details", to="webapp_product.webproduct"
            ),
        ),
    ]
