# Generated by Django 4.2.16 on 2025-06-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp_product", "0004_alter_webproduct_layer_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webproduct",
            name="metadata_five_value",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="webproduct",
            name="metadata_four_value",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="webproduct",
            name="metadata_one_value",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="webproduct",
            name="metadata_six_value",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="webproduct",
            name="metadata_three_value",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="webproduct",
            name="metadata_two_value",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
