# Generated by Django 4.2.16 on 2025-08-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp_product", "0005_alter_webproduct_metadata_five_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webproduct",
            name="metadata_seven_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_seven_value",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
