# Generated by Django 4.2.16 on 2026-10-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp_product", "0006_webproduct_metadata_seven_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webproduct",
            name="metadata_eight_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_eight_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_eight_value",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_five_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_four_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_nine_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_nine_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_nine_value",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_one_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_seven_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_six_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_ten_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_ten_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_ten_value",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_three_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_two_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
