# Generated by Django 4.2.16 on 2026-10-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp_product", "0007_webproduct_metadata_eight_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webproduct",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="webapp_product/"),
        ),
    ]
