# Generated by Django 4.2.16 on 2026-10-06 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp_product", "0008_webproduct_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webproduct",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="webapp_product/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "png", "jpg", "jpeg", "gif", "webp", "svg"]
                    )
                ],
            ),
        ),
    ]
