# Generated by Django 4.2.16 on 2025-03-10 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("country", "0004_delete_customuser"),
        ("project", "0004_remove_project_content_project_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "display_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("access_url", models.CharField(blank=True, max_length=255, null=True)),
                ("publicly_available", models.BooleanField()),
                ("maintainer", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "maintainer_contact",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_id",
                        to="country.country",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_id",
                        to="project.project",
                    ),
                ),
            ],
        ),
    ]
