# Generated by Django 4.2.16 on 2025-03-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="display_image_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
