# Generated by Django 4.2.16 on 2024-09-06 02:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submenu_2", "0003_submenu2_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubMenu1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "children",
                    models.ManyToManyField(
                        related_name="submenu2", to="submenu_2.submenu2"
                    ),
                ),
            ],
        ),
    ]
