# Generated by Django 4.2.16 on 2024-09-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submenu_2", "0003_submenu2_content"),
        ("submenu_1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submenu1",
            name="children",
            field=models.ManyToManyField(
                blank=True, related_name="submenu2", to="submenu_2.submenu2"
            ),
        ),
    ]
