# Generated by Django 4.2.16 on 2025-03-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0016_layerwebmap_table_variable_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layerwebmap",
            name="get_map_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="layerwebmap",
            name="legend_url",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="layerwebmap",
            name="on_click_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="layerwebmap",
            name="specific_timestemps",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="layerwebmap",
            name="table_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="layerwebmap",
            name="timeseries_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="layerwebmap",
            name="url",
            field=models.CharField(max_length=500),
        ),
    ]
