# Generated by Django 4.2.16 on 2025-03-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0017_alter_layerwebmap_get_map_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="layerwebmap",
            name="restricted",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
