# Generated by Django 4.2.16 on 2025-03-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0018_layerwebmap_restricted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layerwebmap",
            name="has_height",
        ),
        migrations.RemoveField(
            model_name="layerwebmap",
            name="on_click_url",
        ),
    ]
