# Generated by Django 4.2.16 on 2025-04-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0019_remove_layerwebmap_has_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layerwebmap",
            name="specific_timestemps",
            field=models.TextField(blank=True, null=True),
        ),
    ]
