# Generated by Django 4.2.16 on 2025-06-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0020_alter_layerwebmap_specific_timestemps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layerwebmap",
            name="url",
            field=models.CharField(max_length=2000),
        ),
    ]
