# Generated by Django 4.2.16 on 2025-06-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0021_alter_layerwebmap_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layerwebmap",
            name="composite_layer_id",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="layerwebmap",
            name="get_map_names",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="layerwebmap",
            name="get_map_url",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="layerwebmap",
            name="table_url",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="layerwebmap",
            name="table_variable_label",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="layerwebmap",
            name="table_variables",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="layerwebmap",
            name="timeseries_url",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="layerwebmap",
            name="timeseries_variable_label",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="layerwebmap",
            name="timeseries_variables",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
