# Generated by Django 4.2.16 on 2025-08-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0023_layerwebmap_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="layerwebmap",
            name="cog_params",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="layerwebmap",
            name="enable_cog",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
