# Generated by Django 4.2.16 on 2025-08-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0024_layerwebmap_cog_params_layerwebmap_enable_cog"),
    ]

    operations = [
        migrations.AddField(
            model_name="layerwebmap",
            name="no_of_plots",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
