# Generated by Django 4.2.16 on 2025-08-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0025_layerwebmap_no_of_plots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layerwebmap",
            name="no_of_plots",
            field=models.FloatField(default=999),
        ),
    ]
