# Generated by Django 4.2.16 on 2025-11-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0027_alter_layerwebmap_no_of_plots"),
    ]

    operations = [
        migrations.AddField(
            model_name="layerwebmap",
            name="unit_conversion",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
