# Generated by Django 4.2.16 on 2026-10-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0028_layerwebmap_unit_conversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="layerwebmap",
            name="depth_values",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
