# Generated by Django 4.2.16 on 2026-10-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description_enabled", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_enabled", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="notice/"),
                ),
                ("url_enabled", models.BooleanField(default=True)),
                ("url", models.URLField(blank=True, max_length=2000, null=True)),
                ("enabled", models.BooleanField(default=True)),
            ],
        ),
    ]
