# Generated by Django 4.2.16 on 2025-03-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tailored_product",
        ),
    ]
