# Generated by Django 4.2.16 on 2025-03-03 23:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_remove_project_tailored_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="content",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
