# Generated by Django 4.2.16 on 2025-03-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp_product", "0004_alter_webproduct_layer_information"),
        ("project", "0003_project_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="content",
        ),
        migrations.AddField(
            model_name="project",
            name="content",
            field=models.ManyToManyField(
                blank=True, related_name="web_products2", to="webapp_product.webproduct"
            ),
        ),
    ]
