# Generated by Django 4.2.16 on 2025-09-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="enabled",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
