# Generated by Django 4.2.16 on 2026-10-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="display_image",
            field=models.ImageField(blank=True, null=True, upload_to="widget/"),
        ),
    ]
